#include "vr-tracks.h"
#define WOODEN_ANGLEHEIGHT	1.5f

#define LEFT_BANK	1
#define RIGHT_BANK	2

void DrawWoodenRC_00(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_04(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_05(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_06(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_07(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_08(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_09(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0A(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0B(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0C(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0D(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0E(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_0F(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_10(int rideIndex, int colorIndex);
void DrawWoodenRC_11(int rideIndex, int colorIndex);
void DrawWoodenRC_12(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_13(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_14(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_15(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_16(int rideIndex, int colorIndex);
void DrawWoodenRC_17(int rideIndex, int colorIndex);
void DrawWoodenRC_18(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_19(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1A(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1B(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1C(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1D(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1E(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_1F(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_20(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_21(int rideIndex, int colorIndex, bool isDiag);
void DrawWoodenRC_22(int rideIndex, int colorIndex);
void DrawWoodenRC_23(int rideIndex, int colorIndex);
void DrawWoodenRC_24(int rideIndex, int colorIndex);
void DrawWoodenRC_25(int rideIndex, int colorIndex);
void DrawWoodenRC_26(int rideIndex, int colorIndex);
void DrawWoodenRC_27(int rideIndex, int colorIndex);
void DrawWoodenRC_2A(int rideIndex, int colorIndex);
void DrawWoodenRC_2B(int rideIndex, int colorIndex);
void DrawWoodenRC_2C(int rideIndex, int colorIndex);
void DrawWoodenRC_2D(int rideIndex, int colorIndex);
void DrawWoodenRC_2E(int rideIndex, int colorIndex);
void DrawWoodenRC_2F(int rideIndex, int colorIndex);
void DrawWoodenRC_30(int rideIndex, int colorIndex);
void DrawWoodenRC_31(int rideIndex, int colorIndex);
void DrawWoodenRC_85(int rideIndex, int colorIndex);
void DrawWoodenRC_86(int rideIndex, int colorIndex);
void DrawWoodenRC_87(int rideIndex, int colorIndex);
void DrawWoodenRC_88(int rideIndex, int colorIndex);
void DrawWoodenRC_89(int rideIndex, int colorIndex);
void DrawWoodenRC_8A(int rideIndex, int colorIndex);
void DrawWoodenRC_8B(int rideIndex, int colorIndex);
void DrawWoodenRC_8C(int rideIndex, int colorIndex);
void DrawWoodenRC_8D(int rideIndex, int colorIndex);
void DrawWoodenRC_8E(int rideIndex, int colorIndex);
void DrawWoodenRC_8F(int rideIndex, int colorIndex);
void DrawWoodenRC_90(int rideIndex, int colorIndex);
void DrawWoodenRC_91(int rideIndex, int colorIndex);
void DrawWoodenRC_93(int rideIndex, int colorIndex);
void DrawWoodenRC_94(int rideIndex, int colorIndex);
void DrawWoodenRC_95(int rideIndex, int colorIndex);
void DrawWoodenRC_96(int rideIndex, int colorIndex);
void DrawWoodenRC_97(int rideIndex, int colorIndex);
void DrawWoodenRC_99(int rideIndex, int colorIndex);
void DrawWoodenRC_9E(int rideIndex, int colorIndex);
void DrawWoodenRC_9F(int rideIndex, int colorIndex);
void DrawWoodenRC_A0(int rideIndex, int colorIndex);
void DrawWoodenRC_A1(int rideIndex, int colorIndex);
void DrawWoodenRC_A2(int rideIndex, int colorIndex);
void DrawWoodenRC_A3(int rideIndex, int colorIndex);
void DrawWoodenRC_A4(int rideIndex, int colorIndex);
void DrawWoodenRC_A5(int rideIndex, int colorIndex);
void DrawWoodenRC_A6(int rideIndex, int colorIndex);
void DrawWoodenRC_A7(int rideIndex, int colorIndex);
void DrawWoodenRC_A8(int rideIndex, int colorIndex);
void DrawWoodenRC_A9(int rideIndex, int colorIndex);
void DrawWoodenRC_AA(int rideIndex, int colorIndex);
void DrawWoodenRC_AB(int rideIndex, int colorIndex);